In [2]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b=np.array([[1.8,5.0,6.0],[1.6,1.5,1.9]])

In [4]:
print(b)

[[1.8 5.  6. ]
 [1.6 1.5 1.9]]


In [5]:
a.ndim

1

In [6]:
# get dimension
b.ndim

2

In [7]:
#get shape
b.shape

(2, 3)

In [8]:
#get type
b.dtype

dtype('float64')

In [9]:
#get size
a.itemsize

4

In [11]:
# get total size
a.size*a.itemsize

12

In [12]:
a.nbytes

12

# Accesing / changing specific elements,rows,colomn,etc

In [18]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
# get a specific element(R,C)
a[1,5]

13

In [17]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# get a specific column
a[:,3]

array([ 4, 11])

In [23]:
# getting little more fancy  [startindex:endindex:step]
a[1,:8:2]


array([ 8, 10, 12, 14])

In [25]:
a[1,5]

13

In [26]:
a[1,6]=17

In [27]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 17]])

In [28]:
a[:,5]=1,8

In [29]:
a

array([[ 1,  2,  3,  4,  5,  1,  7],
       [ 8,  9, 10, 11, 12,  8, 17]])

In [40]:
# 3-D example
d=np.array([[[1,8],[2,9]],[[3,10],[4,11]]])
print(d)

[[[ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]]]


In [38]:
type(d)

numpy.ndarray

In [41]:
# det a specific element (work outside in)
d[1,0,1]

10

In [49]:
d[:,1,:]

array([[ 2,  9],
       [ 4, 11]])

In [52]:
# replace
d[:,1,:]=[[1,7],[4,3]]
d

array([[[ 1,  8],
        [ 1,  7]],

       [[ 3, 10],
        [ 4,  3]]])

# Initilizing diff types of array

In [53]:
#all zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
#all ones marix
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [60]:
# Any other number
np.full((2,2),12)

array([[12, 12],
       [12, 12]])

In [63]:
# any other number(FULL_LIKE)
np.full_like((a),4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
#random decimals\
np.random.rand(4,2)*100

array([[77.379816  , 23.18440611],
       [49.39995667, 69.75122555],
       [49.18224967, 19.70437179],
       [15.25375853, 63.77988006]])

In [68]:
# random integer values

In [70]:
np.random.randint(10,size=(3,3))

array([[1, 8, 2],
       [5, 8, 5],
       [3, 1, 9]])

In [72]:
#identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [85]:
#repeat arry
arr=np.array([[1,5,9]])
print(arr)
np.repeat(arr,3,axis=0)

[[1 5 9]]


array([[1, 5, 9],
       [1, 5, 9],
       [1, 5, 9]])

In [95]:
out=np.ones((5,5))
out

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [94]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
z[1,1]=9

In [98]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [99]:
out[1:4,1:4]=z

In [100]:
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# BE careful when copying arrays

In [101]:
a=np.array([1,2,3])

In [102]:
b=a

In [104]:
b[0]=5

In [105]:
b

array([5, 2, 3])

In [106]:
a

array([5, 2, 3])

In [107]:
b=a.copy()

In [108]:
b

array([5, 2, 3])

In [109]:
a

array([5, 2, 3])

In [110]:
b[2]=10

In [111]:
b

array([ 5,  2, 10])

In [112]:
a

array([5, 2, 3])

# Mathematics

In [115]:
a=np.array([1,2,3,4])

In [123]:
a+=2
a

array([ 7,  8,  9, 10])

In [117]:
a-3

array([-2, -1,  0,  1])

In [119]:
a/10

array([0.1, 0.2, 0.3, 0.4])

In [120]:
a*25

array([ 25,  50,  75, 100])

In [124]:
b=np.array([1,0,1,0])

In [125]:
a+b

array([ 8,  8, 10, 10])

In [127]:
(a+b)**2

array([ 64,  64, 100, 100], dtype=int32)

In [130]:
#sin
np.sin((a+b))

array([ 0.98935825,  0.98935825, -0.54402111, -0.54402111])

# Linear Algebra

In [138]:
c=np.ones((2,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]


In [139]:
f=np.full((3,2),2)
f

array([[2, 2],
       [2, 2],
       [2, 2]])

In [140]:
np.matmul(c,f)

array([[6., 6.],
       [6., 6.]])

In [142]:
# Find the determinant
c=np.identity(10)
np.linalg.det(c)

1.0

# Statistics

In [3]:
stats=np.array([[1,2,3],[4,5,6]])

In [4]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.max(stats,axis=1)

array([3, 6])

In [7]:
np.min(stats,axis=1)

array([1, 4])

In [10]:
np.sum(stats,axis=1)

array([ 6, 15])

# Reorganising arrays

In [11]:
before=np.array([[1,2,3,4],
                [5,6,7,8]])

In [12]:
before.shape

(2, 4)

In [13]:
after=before.reshape(2,2,2)

In [14]:
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
 # verticall stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([4,5,6,7])
                 

In [22]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

# Boolean masking and Advance Indexing

In [31]:
filedata=np.array([1,2,55,3,6,99,5,52,41,6,8,99,412,566,8,5,6,6,77,65,22,30,41,301,456,785,
                  1,5,5,99,77,52,43,10,12,45,62,96,5,455,556,41,4,9,65,6,5,5,55,25,36,44])

In [32]:
print(filedata)

[  1   2  55   3   6  99   5  52  41   6   8  99 412 566   8   5   6   6
  77  65  22  30  41 301 456 785   1   5   5  99  77  52  43  10  12  45
  62  96   5 455 556  41   4   9  65   6   5   5  55  25  36  44]


In [37]:
filedata[filedata>45]

array([ 55,  99,  52,  99, 412, 566,  77,  65, 301, 456, 785,  99,  77,
        52,  62,  96, 455, 556,  65,  55])

In [42]:
# you can index list in numpy
filedata[[1,10,25]]
         

array([  2,   8, 785])

In [47]:
np.all(filedata>55,axis=0)

False

In [53]:
((filedata>50) & (filedata<100))

array([False, False,  True, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
        True,  True, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False])

In [55]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])

In [58]:
a.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
a[[10,11,15,16]]

array([11, 12, 16, 17])

In [64]:
a[[1,7,13,19]]

array([ 2,  8, 14, 20])

In [65]:
a[[3,4,23,24,28,29]]

array([ 4,  5, 24, 25, 29, 30])